### ISSUE TITLE
testFdGreeks support for theta approximation

### ISSUE THREAD

**Issue by quant1729** [amaggiulli/qlnet#110]
Hello Andrea, 

Thank you for your work on QLNet. Really appreciate it. Wanted to clarify one moment with testFdGreeks test. I have noticed that theta approximation in the test is commented out. I stumbled upon this test while trying to figure out why my theta approximation code returns zeros (effectively the same code you have commented in your test). Seems like if I set new evaluationDate up for reevaluation, it is not picked up by the QLNet on my next call .NPV(). Is this a known issue?

Thank you,
Pavel

**Comment by amaggiulli** [comment]
Hi Pavel , than you for your appreciation . 
I think the code commented in T_AmericanOption and T_DividendOption was introduced in the middle of events refactory done some time ago. I have removed the comments and the code work now ( theta pertubation ). I will commit now . So there is no problem for data reevaluation , let me know if I can help you more .

**Comment by quant1729** [comment]
Thank you a lot for such a quick reply. May I ask you to make a nuget release from your latest changes? I am using your library via nuget, and it would be great just to update the link. Thank you.

**Comment by amaggiulli** [comment]
Release 1.9 is on the way ,  I have some work to finish then I will publish the new version.  Anyway I think that the nuget version of the library ( 1.8.0 ) works too.

**Comment by amaggiulli** [comment]
I check better and see there is a problem in theta calculation not regarding the date reevaluation ,  going to test more , I will let you know :)

**Comment by amaggiulli** [comment]
Ok , I understand now . Problem is that FD Engines ( FDStepConditionEngine , FDMultiPeriodEngine... ) do not calculate theta , so no pertubation can be done on a value not calculated . Actually theta is calculated only in the following engines :

AnalyticContinuousGeometricAveragePriceAsianEngine
AnalyticDiscreteGeometricAveragePriceAsianEngine
ForwardPerformanceVanillaEngine
ForwardVanillaEngine
AnalyticDividendEuropeanEngine
AnalyticEuropeanEngine
baroneadesiwhaleyengine
binomialengine
bjerksundstenslandengine
Juquadraticengine

**Comment by quant1729** [comment]
Thank you. It is clear. What I am doing is basically is I want to approximate greeks (incl. theta) for models that dont produce it. e.g. CrankNicolsonFD. 

In case of theta I am shifting the evaluationDate and rerun the calculations (calling .NPV()). I get exact same number (npv) back, as if new evaluationDate was not used in new calculations. If I recreate all the classes for new calculation (yield term struct, process, vanilla option, engine) and run the calculation, then I get back correct new NPV.

**Comment by amaggiulli** [comment]
Ok , then what you have to check is that your process register with date update.

**Comment by quant1729** [comment]
Can you please elaborate on this? How this should be done? I am following very basic example by Luigi here - https://www.youtube.com/watch?v=MgUlBB59Ll0

**Comment by amaggiulli** [comment]
What you have to use is something like : 
`process_.registerWith(update);` ( look AnalyticDividendEuropeanEngine ctor )
To better help you consider PR a test case based on what you want to achieve

**Comment by quant1729** [comment]
Frankly I dont understand your suggestion. Let me suggest a test case: 
1. I would like to estimate theta for option using CrankNicolsonFD model. In order to do so, it is enough just to calculate NPV of the option for today and for tomorrow. Resulting approximation formula is simple. 

In terms of code, this is what I expect to return non-zero theta. It is effectively a C# version of Python code on the Luigi's video that I sent you. Please find it below. Currently this code returns zero theta which is not correct result. 

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using QLNet;

namespace EquityOption
{
    class EquityOption
    {
        static void Main(string[] args)
        {

            DateTime timer = DateTime.Now;

            // set up dates
            Calendar calendar = new TARGET();
            Date todaysDate = new Date(15, Month.May, 1998);
            Date settlementDate = new Date(17, Month.May, 1998);
            Settings.setEvaluationDate(todaysDate);

            // our options
            Option.Type type = Option.Type.Put;
            double underlying = 36;
            double strike = 40;
            double dividendYield = 0.00;
            double riskFreeRate = 0.06;
            double volatility = 0.20;
            Date maturity = new Date(17, Month.May, 1999);
            DayCounter dayCounter = new Actual365Fixed();

            Console.WriteLine("Option type = " + type);
            Console.WriteLine("Maturity = " + maturity);
            Console.WriteLine("Underlying price = " + underlying);
            Console.WriteLine("Strike = " + strike);
            Console.WriteLine("Risk-free interest rate = {0:0.000000%}", riskFreeRate);
            Console.WriteLine("Dividend yield = {0:0.000000%}", dividendYield);
            Console.WriteLine("Volatility = {0:0.000000%}", volatility);
            Console.Write("\n");

            string method;

            Console.Write("\n");

            // write column headings
            int[] widths = new int[] { 35, 14, 14, 14 };
            Console.Write("{0,-" + widths[0] + "}", "Method");
            Console.Write("{0,-" + widths[1] + "}", "European");
            Console.WriteLine("{0,-" + widths[3] + "}", "American");

            List<Date> exerciseDates = new List<Date>(); ;
            for (int i = 1; i <= 4; i++)
                exerciseDates.Add(settlementDate + new Period(3 * i, TimeUnit.Months));

            Exercise europeanExercise = new EuropeanExercise(maturity);
            Exercise bermudanExercise = new BermudanExercise(exerciseDates);
            Exercise americanExercise = new AmericanExercise(settlementDate, maturity);

            Handle<Quote> underlyingH = new Handle<Quote>(new SimpleQuote(underlying));

            // bootstrap the yield/dividend/vol curves
            var flatTermStructure = new Handle<YieldTermStructure>(new FlatForward(settlementDate, riskFreeRate, dayCounter));
            var flatDividendTS = new Handle<YieldTermStructure>(new FlatForward(settlementDate, dividendYield, dayCounter));
            var flatVolTS = new Handle<BlackVolTermStructure>(new BlackConstantVol(settlementDate, calendar, volatility, dayCounter));
            StrikedTypePayoff payoff = new PlainVanillaPayoff(type, strike);
            var bsmProcess = new BlackScholesMertonProcess(underlyingH, flatDividendTS, flatTermStructure, flatVolTS);

            // options
            VanillaOption europeanOption = new VanillaOption(payoff, europeanExercise);
            VanillaOption americanOption = new VanillaOption(payoff, americanExercise);

            // Finite differences
            int timeSteps = 801;
            method = "Finite differences";
            europeanOption.setPricingEngine(new FDEuropeanEngine(bsmProcess, timeSteps, timeSteps - 1));
            americanOption.setPricingEngine(new FDAmericanEngine(bsmProcess, timeSteps, timeSteps - 1));

            Console.Write("{0,-" + widths[0] + "}", method);
            Console.Write("{0,-" + widths[1] + ":0.000000}", europeanOption.NPV());
            Console.WriteLine("{0,-" + widths[3] + ":0.000000}", americanOption.NPV());


            // Now approximating theta
            var step = 1.0 / 365.0;
            var npv = americanOption.NPV();
            var newSettlementdate = settlementDate - new Period(1, TimeUnit.Days);
            Settings.setEvaluationDate(newSettlementdate);
            var npvMinus = americanOption.NPV();
            Settings.setEvaluationDate(settlementDate);

            var thetaAppr =  (npv - npvMinus) / step;

            Console.WriteLine("Theta (approximated): {0}", thetaAppr);

            Console.Write("Press any key to continue ...");
            Console.ReadKey();
        }
    }
}`

**Comment by amaggiulli** [comment]
Working on it, thank you for the code

**Comment by amaggiulli** [comment]
Got it ! =)

Error is in flatTermStructure construction : 

`var flatTermStructure = new Handle<YieldTermStructure>(new FlatForward(settlementDate, riskFreeRate, dayCounter));`

Using this FlatForward constructor , the termstructure use a fixed referenceDate = settlementDate 

To link termstructure to evaluationdate changes use : 

`var flatTermStructure = new Handle<YieldTermStructure>(new FlatForward( 0, calendar, new SimpleQuote( riskFreeRate ), dayCounter ));` ( as Luigi video also show )

The same thing apply for the volatility.

Let me know how goes

**Comment by quant1729** [comment]
Wow! Thank you for help. I was looking for some subtle convention, but couldn't find it myself. I think it's worth documenting this moment somehow, make it explicit. maybe even in the original option example. I guess many users may have similar problems. 

Thank you for help, Andrea. Much appreciated.

**Comment by amaggiulli** [comment]
You welcome Pavel , if you develop the approximate greeks , or want to document the code please consider contribute .
