### ISSUE TITLE
Improvement idea: Use specific type for exceptions

### ISSUE THREAD

**Issue by Askolein** [amaggiulli/QLNet#112]
Hi, 

It would be very useful for exception handling if the following utils:

_Utils.QL_REQUIRE_

throws a dedicated type of exception instead of the generic System.Exception. C#6 and C#7 have lots of goodies to handle exceptions by type and QLNet ones cannot be differentiate easily.

Change is minor:
 * Create an exception class that inherits System.Exception
 * Change the "_Utils.QL_REQUIRE_" code to generate this new type instead

What do you think?

PS: having two new Exception types would be even better. One for QL_REQUIRE and another for QL_FAIL.

**Comment by amaggiulli** [comment]
+1 for the 2 exception

**Comment by igitur** [comment]
I also support this, but I think the exceptions should be more granular than just QL_REQUIRE and QL_FAIL. For example, an exception for missing / wrong inputs. Another exception for calculation error. etc.

**Comment by Askolein** [comment]
Totally agree on the "more granular" idea. Also, exception could be filled with context property like strike, dates, ... so that we do not only rely on the message it self to get the information.

But I'd say: step by step.

**Comment by amaggiulli** [comment]
https://github.com/amaggiulli/QLNet/commit/39d4390d8c11cb2d62c280a78807cefba1c99e27
