### ISSUE TITLE
Build and publish to different .net framework

### ISSUE THREAD

**Issue by amaggiulli** [amaggiulli/QLNet#117]
Organize project solutions to obtain a Nuget package with multiple target framework like this : 

![libs](https://cloud.githubusercontent.com/assets/5287576/22251789/51e257da-e24c-11e6-8b8c-d84e725c8c7b.JPG)

**Comment by screig** [comment]
How and where does the building of the nuget package happen at the moment?

internally, where I work I do something like so:

NuGet.exe pack _CENTRAL\SomeName\SomeName.csproj -Properties Configuration=Release -Version 1.%comlib_version%.0 -Verbosity "Detailed" -Exclude "FodyWeavers.xml" -OutputDirectory "%WORKSPACE%\__NugetPackages"

You can also do it off the nuspec file

**Comment by amaggiulli** [comment]
On AppVeyor : https://ci.appveyor.com/project/amaggiulli/qlnet

**Comment by screig** [comment]
Ok cool

After this line:

msbuild "C:\projects\qlnet\QLNet.sln" /verbosity:minimal /logger:"C:\Program 

just need to also build the netcore solution, then we just add a line to the nuspec file to also include the dll (built from the net core solution) in to the package. Like so 

.....
 </dependencies>
    </metadata>
	<files>
		<file src="bin\Release\netcore.dll" target="lib\**netcore** (correct name ?) " />
	</files>
</package>



will do this tonight

**Comment by screig** [comment]
</dependencies>
    </metadata>
	<files>
		<file src="bin\Release\netcore.dll" target="lib\netcore " />
	</files>

</package>

**Comment by amaggiulli** [comment]
I looked at JSon.Net and there are different solution/project files for every version, we have to do something similar ?

**Comment by screig** [comment]
on the main solution file, you can do a batch build config. So when you build the main solution it produces binaries for net framework x to y. Depending on what can be built.  They should all appear in different release folders under the bin folder of the main solution. Nuget will either pick them up dynamically, if not they can be specified like so:

    <file src="bin\Release\SameName.dll" target="lib\version <X to Y> " />

where for each build done you change the location. As the net core has its own sol, that needs to be built separately, and then just explicitly reference the created dll. 

So do you think QLnet can be compiled to all the frameworks in the picture at the top?

**Comment by screig** [comment]
sorry Im incorrect on that, will need a solution file for each framework I think.

**Comment by screig** [comment]
http://shazwazza.com/post/multi-targeting-a-single-net-project-to-build-for-different-framework-versions/

**Comment by amaggiulli** [comment]
Great , yes I think we can compile for all target . I start some test now , for older version of the framework we can do a macro that enable/disable features ( like System.Numerics based classes that works only on 4.0+ ).

**Comment by screig** [comment]
Seeing that .....

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The primary reference "System.Core", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v2.0". To resolve this problem, either remove the reference "System.Core" or retarget your application to a framework version which contains "System.Core".	QLNet	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1820	

Warning		The primary reference "System.Numerics", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v2.0". To resolve this problem, either remove the reference "System.Numerics" or retarget your application to a framework version which contains "System.Numerics".	QLNet	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1820

**Comment by amaggiulli** [comment]
Maybe we can start with 4.0 , 4.5 and 4.6..

**Comment by screig** [comment]
sure

**Comment by screig** [comment]
made a pull request, not appvoyer needs to tweaked.

**Comment by amaggiulli** [comment]
Some minor problems on AppVeyor but I think we got it , thx @screig for support .
Please NET Core users  let me know if nuget "Install-Package QLNet" it works on NET Core solutions

**Comment by screig** [comment]
Cool, I will try this
