### ISSUE TITLE
Documentation for user manual and list of functions

### ISSUE THREAD

**Issue by hamidsharifi** [amaggiulli/QLNet#119]
hi dear
how can I have a documentation or user manual for QLNet that has list of all functions. also I need to use Covariance of two array(with equal row), but I don't know how I must write.
thx

**Comment by amaggiulli** [comment]
Sorry, QLNet have no manuals at the moment , basic informations are inside the code as comments.

**Comment by igitur** [comment]
My advice is look at the Quantlib documentation and then look to see if the part you're interested in has been ported to qlnet
