### ISSUE TITLE
Floating numbers equality

### ISSUE THREAD

**Issue by amaggiulli** [amaggiulli/QLNet#120]
I have enabled another tool for code analysis , SonarQube , you can check it here [https://sonarqube.com/dashboard/index?id=QLNet-develop](url). This tool, like Resharper , bother about floating point comparison so I developed a double extension to compare doubles (fcfbb62906db71ef18e37f3a027770487f370dc6) , from my tests the overhead is very low but if someone know a fastest way to do it let me know . From now on to compare 2 double instead of 

`if ( val1 == val2 ) `
`if ( val1 != val2 ) ` 
use
`if ( val1.IsEqual(val2 )`
`if ( val1.IsNotEqual(val2 )`

**Comment by igitur** [comment]
What was wrong with normal `==` ?

**Comment by amaggiulli** [comment]
Resharper : https://www.jetbrains.com/help/resharper/2016.3/CompareOfFloatsByEqualityOperator.html
SonarQube : https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1244

**Comment by igitur** [comment]
I understand that floating point operations aren't exact and therefore `==` is dangerous to use, but how does `.IsEqual()` solve that? Doesn't that just hide the problem from Resharper and SonarQube?

**Comment by amaggiulli** [comment]
Absolutely not , IsEqual is implemented like that : 
`if (Math.Abs(d1 - d2) <= double.Epsilon)
            return true;
 return false;`

instead of direct comparison use a tolerance to check the difference

**Comment by igitur** [comment]
Sorry, I was thinking of `Equals()`. Didn't notice that you added an extension method for `IsEqual()`.
