### ISSUE TITLE
clone() for BmaIndex

### ISSUE THREAD

**Issue by datametrics** [amaggiulli/QLNet#122]
..would be nice to have a clone method in BmaIndex like

`public virtual BMAIndex clone(Handle<YieldTermStructure> forwarding)
        {
            return new BMAIndex(forwarding);
        }`

thx!

**Comment by tournierjc** [comment]
Hello,

What for as `newIndex = index.clone(fwd);` will be equivalent to `newIndex = new BMAIndex(fwd);`?
