### ISSUE TITLE
ConvertibleBond arguments

### ISSUE THREAD

**Issue by datametrics** [amaggiulli/QLNet#123]
There seems to be an issue with the cast to convertiblebond price engine arguments:

At this point moreargs will be null since

`
public override void setupArguments(IPricingEngineArguments args){
           base.setupArguments(args);
           ConvertibleBond.option.arguments moreArgs = args as ConvertibleBond.option.arguments;
           Utils.QL_REQUIRE( moreArgs != null, () => "wrong argument type" );
           moreArgs.conversionRatio = conversionRatio_;
`

I helped myself with an additional creator method in ConvertibleBond.option.argument-Class:

` 
internal static arguments Create(IPricingEngineArguments args)
 {
Arguments oarg = args as Arguments;
 return new arguments()
{
 payoff = oarg.payoff,
  exercise = oarg.exercise,
};
}
`

which i then use in setupArguments() like this:

`  
public override void setupArguments(IPricingEngineArguments args)
{
base.setupArguments(args);
arguments moreArgs = arguments.Create(args);
Utils.QL_REQUIRE(moreArgs != null, () => "wrong argument type");
`

Anyway, the arguments ctor has to be equipped with some initializers:

` 
public class arguments : OneAssetOption.Arguments
         {
            public arguments()
            {
                    conversionRatio = null;
                    settlementDays = null;
                    redemption= null;
                     callabilityDates = new List<Date>();
                    callabilityTypes = new List<Callability.Type>();
                    callabilityPrices = new List<double>();
                    callabilityTriggers = new List<double?>();
                    couponDates = new List<Date>();
                    couponAmounts = new List<double>();
                    dividendDates = new List<Date>();
                    dividends = new DividendSchedule();
                }
`

regards..

**Comment by amaggiulli** [comment]
I dont think the problem is the cast , but just the lists that are not initialized . A fix will follow
