### ISSUE TITLE
QLNet With Examples dont compile anymore

### ISSUE THREAD

**Issue by FredericDgrv** [amaggiulli/QLNet#129]
Building QLNet.csproj in QLNet_with_Examples.sln is no longer possible since DotNet Core integration.

Error :  
Severity	Code	Description	Project	File	Line	Suppression State
Error		Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.	QLNet	C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets	140	

Thx

**Comment by amaggiulli** [comment]
What version of VS are you using ? I can compile QLNet_with_Examples.sln with VS 2012 and Vs 2015 without errors.

**Comment by FredericDgrv** [comment]
Microsoft Visual Studio Community 2015 Version 14.0.25431.01 Update 3 (no available update at the moment).

I did a try with VS 2013 Professional at work and it worked perfectly...
I didn't find why it wants so badly project.json...

Below output with activated verbose log:

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
Restoring packages for 'Test'.
Restoring packages for 'QLNet'.
The project QLNet does not specify any target frameworks in C:\dev.others\quant\qlnet\QLNet\QLNet.project.json.
The project Test does not specify any target frameworks in C:\dev.others\quant\qlnet\Test\Test.project.json.
Package restore failed for 'QLNet'.
Package restore failed for 'Test'.
Lock file has not changed. Skipping lock file write. Path: C:\dev.others\quant\qlnet\QLNet\QLNet.project.lock.json
Writing lock file to disk. Path: C:\dev.others\quant\qlnet\Test\Test.project.lock.json
NuGet Package restore finished for project 'Test'.
NuGet Package restore finished for project 'QLNet'.
NuGet package restore failed.
1>------ Rebuild All started: Project: QLNet, Configuration: Debug Any CPU ------
1>Build started 20/02/2017 21:59:53.
1>Building with tools version "14.0".
1>Project file contains ToolsVersion="4.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="14.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
1>Target "_CheckForInvalidConfigurationAndPlatform" in file "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets" from project "C:\dev.others\quant\qlnet\QLNet\QLNet.csproj" (entry point):
1>Task "Error" skipped, due to false condition; ( '$(_InvalidConfigurationError)' == 'true' ) was evaluated as ( '' == 'true' ).
1>Task "Warning" skipped, due to false condition; ( '$(_InvalidConfigurationWarning)' == 'true' ) was evaluated as ( '' == 'true' ).
1>Using "Message" task from assembly "Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>Task "Message"
1>  Configuration=Debug
1>Done executing task "Message".
1>Task "Message"
1>  Platform=AnyCPU
1>Done executing task "Message".
[...]

**Comment by amaggiulli** [comment]
Are you on branch develop ? Have you pull the latest changes ? I dont understand why system try restoring NuGet packages ...have you the source code or the dll downloaded by nuget ?

**Comment by FredericDgrv** [comment]
Same behavior on latest source code of master and develop.
No clue either...

I created a new project and installed the Nuget from internet to work on my 
task. It worked well.

**Comment by igitur** [comment]
I had the same issue a while back. Had to delete `*.json`, `QLNet.xproj` and had to restart Visual Studio.

**Comment by amaggiulli** [comment]
yes , deleting qlnet.project.json solve then problem  , too bad not compile anymore the 40 and 45 version ..I'm going crazy to make AppVeyor build all versions..
