### ISSUE TITLE
volatility surfaces and market data

### ISSUE THREAD

**Issue by datametrics** [amaggiulli/QLNet#139]
Hi alltogether,

I've got a question regarding volatility structures.

I'd like to know what the best approach would be to interpolate e.g. a stock vola surface. Given the classes in the lib, I was able to interpolate the surface from fictive implied volatilities of let us say some ATM call options.

That implies that you have to retrieve implied volatilities from the markets. 

But what about retrieving liquid option (or Cap/Floor) premiums an deriving the implied volatilities from these instruments? I mean this should at least yield to the same results.

I found an interesting class in quantlib, that isn't implemented yet in qlnet...the HestonVolatilitySurface. It makes it possible to define the market instruments as calibrationhelpers which looks very similar to the piecewise yieldcurve bootstrapping. The point here is that it also needs the implied volatility at definition time of the helperobject.

Alternatively, I could enter the market iv's retrieved from a dataprovider directly into the surface without using helperobjects (despite the advantages that a Heston calibration offers), right?

What is your best practice? Retriving market iv's and interpolating these or retrieving option premiums and deriving iv's and interpolating?

Regards

**Comment by igitur** [comment]
My recommendation is you ask this on the `QuantLib` forum and if any classes are missing in `QLNet`, let us know. I also ported the `HestonBlackVolSurface` class in #141 . I still have to find a unit test that doesn't require porting a whole bunch of other (finite difference) classes too.

Maybe @amaggiulli  can be more helpful about your question.

**Comment by jiskin** [comment]
Hello, 

The implied volatility are quoted on Bloomberg (for example SX5E Index has SX5E 3M 100 VOL BVOL Index ticker available). They also provide (using DLIB) the results of their volatility surface. However, I'm not always satisfied with their extrapolation.

From this I'm currently working on building a volatility surface from Call/Put quoted options. 
1/ You must start by selecting the most liquid ones (for example by using a criteria on the bid/ask spread) and keeping the good option when the strike is very in or out the money. 

2/ From this, using the "impliedVolatility" function in QLNet, you can estimate the volatility by strike/maturity.

3/ You can reproduce the volatility smile on strikes by maturity, by calibrating a SABR model for example. From this you can estimate the missing point of your datagrid.

4/ With all the points you now have a volatility surface and you can use the "BlackVarianceSurface" object. The last question is to select the interpolation method in your volatility surface. For now, I guess only bicubic is available, remains the question of arbitrage free volatility surface.

In my opinion, this 1/ part is the most touchy one. I'm still reading about the 4/ point regarding the arbitrage question.

Regards,
jiskin

**Comment by datametrics** [comment]
Thanks @igitur for your port. I did some tests and it seems to run very well.

I posted a similar question to usergroup. There i mentioned another issue with missing values in the volatility matrix for the blackvariance surface. What I've found so far is that a laplaceinterpolation generally could be able to deal with missing cells in the vola matrix. SInce i have no quantlib setup and only use qlnet it would be great if the laplaceinterpolation would become part of one of your upcoming implementations. Or is there even another interpolator able to interpolate missing matrix values, i'm not so familiar with that? Maybe i have a try for myself with the port :-)

Yep @jiskin ,fully agree. You mention one interesting point, the SABR / ZABR surfaces. I guess the require a similar setup like Heston.

**Comment by datametrics** [comment]
..gave it a try and ported laplace. I'm sure you would correct some class styling. And unfortunately it doesn't produce meaningful results yes. There is still a bug somewhere because all interpolated values are below 1. 
If you could have a look that would be great!

Regards,

[BicgStab.txt](https://github.com/amaggiulli/QLNet/files/894108/BicgStab.txt)
[LaplaceInterpolation.txt](https://github.com/amaggiulli/QLNet/files/894109/LaplaceInterpolation.txt)

**Comment by igitur** [comment]
Would you mind committing your changes to a new branch in your own fork? I'll check it out from there. 

If you struggle to get the interpolation working, check out chapter 3.8 from [Numerical Recipes, 3rd Edition](https://github.com/yuanhui-yang/Numerical-Recipes/blob/master/Numerical%20Recipes%20-%20The%20Art%20of%20Scientific%20Computing%20-%203rd%20Edition.pdf)

And more info at https://quantlib.wordpress.com/tag/laplace-interpolation/

**Comment by datametrics** [comment]
..unfortunately i got stuck at the sparse_matrix magic, which is integrated part of boost. I thought it could be simply replaced by the matrix class but that was wrong. Porting the > 6000 lines in boost::matrix_sparse will keep me years on the issue :-) 

Real pitty, since the results in my c++ tests look really promising especially for this use case.

**Comment by jiskin** [comment]
Hello @datametrics,

I'm not the one who can say if using Math.Net is possible or not, but Quantlib is using boost and the QLNet library should have a "backup" too...

Do you have the same results with Quantlib and QLNet? 

Do not hesitate to share your code, it could  be interesting for everyone.

jiskin

**Comment by amaggiulli** [comment]
I'm still busy with project refactoring ,  two days more I hope , when finished I will develop the sparse matrix in c#.

**Comment by datametrics** [comment]
Thank you, but take your time. I am able to work with this implementations..

[BicgStab.txt](https://github.com/amaggiulli/QLNet/files/923980/BicgStab.txt)
[LaplaceInterpolation.txt](https://github.com/amaggiulli/QLNet/files/923981/LaplaceInterpolation.txt)

@jiskin yes, i did some tests and also interpolated a complete surface with it. The results look promising even if a considerable edge of the surface input instruments is missing.. wondering how i can use this for swaption volas..

**Comment by tournierjc** [comment]
Hello @datametrics 

Just to let you know I have ported the SparseMatrix implementation and Bicgstab in #172.

I'll appreciate if you can try your example with my implementation as I did not fully test the operator* from SparseMatrix and the Bicgstab port.

**Comment by datametrics** [comment]
Thank you @tournierjc ,

i'm going to test, when I get back to matrix interpolation!
