### ISSUE TITLE
AppVeyor / Sonar verbosity

### ISSUE THREAD

**Issue by igitur** [amaggiulli/QLNet#148]
I notice in AppVeyor log (https://ci.appveyor.com/project/amaggiulli/qlnet-d58o4)

```
sonar.verbose=true was specified - setting the log verbosity to 'Debug'
```

This causes a LOT of output and slows down the browser window refresh. I had a similar issue on another project. Disabling verbose mode would be nice, unless you want the full output.

**Comment by amaggiulli** [comment]
It was disabled before , but new sonar version is bugged , sometimes it fails with not reason , still investigating...

**Comment by amaggiulli** [comment]
Ok , I think I have fixed now , verbosity set back to Info.
