### ISSUE TITLE
Issue with Null<Real>() initial value

### ISSUE THREAD

**Issue by jiskin** [amaggiulli/QLNet#158]
Hello,

In QuantLib, when you initiate a Real value with the Null<Real>, the value will be 3.4028234663852886e+038.

In the QLNet version, we have the double? type to be able to set to null.

If we go to the GaussLobattoIntegral class, we have in QuantLib

```
Real GaussLobattoIntegral::calculateAbsTolerance(
                                     const boost::function<Real (Real)>& f, 
                                     Real a, Real b) const {
        Real relTol = std::max(relAccuracy_, QL_EPSILON);
```

Where relAccuracy_ = 3.4028234663852886e+038 when in QLNet we have 0.0

I had trouble to port the NoArbSabr class because of the integral result was different...

Regards

jiskin

**Comment by amaggiulli** [comment]
double relTol = Math.Max(relAccuracy_ ?? Const.QL_EPSILON, Const.QL_EPSILON);

**Comment by jiskin** [comment]
Hello, 

QL_EPSILON = 2.2204460492503131e-016 which is not the same value. Maybe we can think about QL_REAL_NULL_VALUE = 3.4028234663852886e+038?

**Comment by amaggiulli** [comment]
No , null value is undetermined in c++.
