### ISSUE TITLE
ThreadStatic Settings, event source

### ISSUE THREAD

**Issue by miegler** [amaggiulli/QLNet#174]
Hi,
"eventSource" in the Settings class seems to cause a bottleneck in a highly parallel environment with frequent changes of the evaluation date. I don't see why the "eventSource" is not declared as "[ThreadStatic]", do you agree?

Regards,
Michael

**Comment by igitur** [comment]
Yes, I think you're right.

**Comment by miegler** [comment]
Just took a second look... Won't work if the listening objects (term structures etc) are created from a different thread...

**Comment by tournierjc** [comment]
Maybe it will be solved with the work on generics (generics branch on this repository) where Settings class is refactored as a Singleton ?
