### ISSUE TITLE
Make work with SQLCLR

### ISSUE THREAD

**Issue by coderb** [amaggiulli/QLNet#204]
It would be nice to be able to use QLNet with an assembly that defines functions for use with MS Sql (SQLCLR functions).

For SQLCLR there is a requirement that disallows writable static fields.

Possible solutions include making the fields readonly (eg read settings from a config file and don't allow them to be changed at runtime) or converting static objects to non-static and allowing them to be passed into the necessary methods to override default behavior.

**Comment by amaggiulli** [comment]
will be in the next release "thread safe"

**Comment by coderb** [comment]
right on! :+1: :+1: :+1:
