### ISSUE TITLE
DefaultProbabilityHelper class

### ISSUE THREAD

**Issue by jack1232** [amaggiulli/QLNet#224]
In the original C++ QuantLib or QuantLib C# SWIG version, there is a DefaultProbabilityHelper class, which is a bootstrap helper for default-probability term structures. This class is very useful in calculating the hazard rate and pricing CDS from spread market data. The following link is an example that uses this helper class to pricing CDS: 

http://www.riskreversal.net/cds/

[](http://www.riskreversal.net/cds/)

However, QlNet seems missing it. Any plan to implement this helper class?

Thanks
Jack

**Comment by tournierjc** [comment]
Hi Jack,

In C# the design of this class has been difficult to implement, my pull request is pending for a while now... (#219)

You can use this branch : https://github.com/tournierjc/QLNet/tree/defaultcurves_squashed

**Comment by jack1232** [comment]
Thank you. Will take a look.
