### ISSUE TITLE
Question: Matching QuantLib version

### ISSUE THREAD

**Issue by muichkine** [amaggiulli/QLNet#225]
Hello,

I don't see any reference to QuantLib code in the code tree. 

- Are the two projects totally independent?
- If yes, are fixes/contributions brought to QuantLib ported to QLNet?
- If no, what is the QuantLib version used as the primary fork for QLNet?

Thank you for the feedback.

**Comment by amaggiulli** [comment]
Hi , 

QLNet don'y have any reference in code to Quantlib

- Yes
- Yes
- We keep the two libraries in synch as much as possible

**Comment by muichkine** [comment]
Thank you.
