### ISSUE TITLE
[BUG] GetHashCode of Date class - absent implementation

### ISSUE THREAD

**Issue by QtRoS** [amaggiulli/QLNet#233]
**Describe the bug**
`GetHashCode` method of `Date` class is implemented in the following way:
```
      public override int GetHashCode()
      {
         return 0;
      }
```
So `Date` can't be used as a key in the dictionary. Technically it can but without any speedup (because of collisions). It's a bit strange. I've noticed that in `CashFlow` it is implemented in the following way:
```
      public override int GetHashCode()
      {
         return date().serialNumber();
      }
```
Looks reasonable! Maybe `GetHashCode` in `Date` class should be implemented in the same way? Or simply like:

```
      public override int GetHashCode()
      {
         return date.GetHashCode();
      }
```

**Expected behavior**
Every different `Date` object has unique hash code.

**Comment by amaggiulli** [comment]
Good find ! Feel free to submit a Pull Request that resolve this issue.
