### ISSUE TITLE
[BUG] Optimization method based on line search may return function value that does not correspond to current value

### ISSUE THREAD

**Issue by hhaldn** [amaggiulli/QLNet#252]
For an optimization method based on a line search, the function value may not equal the value of the cost function evaluated at current value, when the method minimize has returned.

I have attached a unit test that reproduces the problem. The test fails when I run it at the current head (@819039a8d91a) corresponding to version 1.11.4.

[T_FinalFuctionValueAndCurrentValue.txt](https://github.com/amaggiulli/QLNet/files/4592579/T_FinalFuctionValueAndCurrentValue.txt)

I suspect that the problem has been around for a while.

The problem seems to be, that you may return from inside the loop in LineSearchBasedMethod.minimize. In this case you will set the function value, but not update the current value.

The test demonstrates the problem for BFGS, but the same problem for the other optimization methods based on LineSearchBasedMethod (e.g. ConjugateGradient and SteepestDescent).

**Comment by amaggiulli** [comment]
Hi @hhaldn , above commit should solve the issue , let me know if that works.
thanks for spotting it

**Comment by hhaldn** [comment]
The commit solves the problem.
