### ISSUE TITLE
[FEATURE] Cleanup Project solution

### ISSUE THREAD

**Issue by amaggiulli** [amaggiulli/QLNet#253]
Update the solution to make easier build/test/deploy
Cleanup roadmap 

- Remove old solution
- Update tests to use only xunit
- Target only netstandard , currently version 1.2 should be good 

Feel free to add notes/comment

**Comment by igitur** [comment]
Can we do a test build first before releasing? I'm old-fashioned and still like a .NET Framework build, so I would just like to test against my projects how `netstandard1.2` works and whether it pulls in additional dependencies.

**Comment by amaggiulli** [comment]
@igitur sure , I'm working on a feature branch, we will test it there once done

**Comment by amaggiulli** [comment]
@igitur you can start your testing using version 1.12.0-preview.24 :

`Install-Package QLNet -Version 1.12.0-preview.24`

**Comment by igitur** [comment]
Thanks I will test soon, but I see you have already merged this?

**Comment by igitur** [comment]
I'm wondering whether we still need the `QAssert` class, since we don't split between XUnit and Microsoft.VisualStudio.TestTools.UnitTesting anymore.
