### ISSUE TITLE
Question:  is it possible to use QLNet for generic MC pricing?

### ISSUE THREAD

**Issue by akasolace** [amaggiulli/QLNet#257]
Let say I have a payoff depending of multiple assets (known volatilities and correlations matrix). Could QLNet be used to price such an option using MC technique? If it is the case, could you point me to a minimal example doing such a pricing?

Thank you

**Comment by amaggiulli** [comment]
Currently there isn't a sample for multiasset pricing but you can find building blocks here :

**Comment by akasolace** [comment]
Thank you
