### ISSUE TITLE
Thread aware calculation of LazyObject

### ISSUE THREAD

**Issue by channell** [amaggiulli/QLNet#258]
**Is your feature request related to a problem? Please describe.**
In parallel execution environments multiple threads can trigger the recalculation of a l LazyObject, but the current implementation sets calculated_ prior to the call to performCalculations() which causes another thread to step over the calculation step and attempt to read the results before they’ve been provided resulting in an ArgumentException error being throw in the second thread.

**Describe the solution you'd like**
1) Introduce a bootstrapping_ guard ThreadStatic member to LazyObject and set it before the call to performCalculations() to prevent recursion during bootstrapping and move to setting of calculated_ to follow calculation.
2) Add a spinLock_ System.Threading.SpinLock to prevent duplicate calls to performCalculations()from different threads

**Describe alternatives you've considered**
Many years ago I developed a wrapper around C++ QuantLib and added locking to my version.. I’m looking to migrate to QLNet for to avoid mutli-mode assembly problem with .NET 5 and improve performance (by avoiding managed/unmanaged transition).
**Additional context**
I’ve made the change on my workstation, and the addition of the SpinLock adds 1% to the runtime of the test suite, but this cost would be recovered by the ability to execute models in parallel.

**Comment by amaggiulli** [comment]
Hey @channell , thx for your PR , I agree with you about the uneeded pattern , what about working togheter to completly remove it from the library ? In the QLNet development we did several hack to avoid this problem with the only result to make the code ugly and difficult to read and without fixing the issue. Let me know if you have any idea on how to proceed.

**Comment by oliviermilla** [comment]
@tournierjc why not do that here as a major version? I mean, It's QLNet + refactoring + some more from QuantLib right?
