### ISSUE TITLE
Use dotnet format instead of astyle

### ISSUE THREAD

**Issue by igitur** [amaggiulli/QLNet#261]
Refer to https://github.com/dotnet/format 

This seems to be a much better .NET code formatter than astyle. Astyle isn't very aware of .NET specific syntax and especially the recently released language features are not always properly formatted with Astyle.

My suggestion is to switch to `dotnet format` for our code formatting. 

Obviously this will have a once-off impact on almost every file, but from what I can tell, these changes are almost all formatting issues that Astyle neglected to address.

e.g. with Astyle:
```c#
"\nvalue:  " + values_cash[n  ] + " for spread: " + spreads[n] +
```

with `dotnet format`
```c#
"\nvalue:  " + values_cash[n] + " for spread: " + spreads[n] +
```

**Comment by amaggiulli** [comment]
👍
