### ISSUE TITLE
Net standard over net 6.0

### ISSUE THREAD

**Issue by screig** [amaggiulli/QLNet#273]
I made a branch to change the library to net standard but it seems I can't commit it.

```
"git" push -u --recurse-submodules=check --progress "origin" refs/heads/net_standard:refs/heads/net_standard
ERROR: Permission to amaggiulli/QLNet.git denied to screig.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Done
```

Anyway, why? Well if the library is in Net6.0 it shuts out users who are tied to the Net Framework. For example I need to use ExcelDNA and therefore am bound to the Net-Framework, as much as I don't want to be. However on the flip side if the library is Net Standard 2.0 (note 2.1 does not support this) then users from both Net-Framework and the Net(Core) spaces can consume the library.

**Comment by amaggiulli** [comment]
will check if I could restore the Multi-targetting, that should solve your issue

**Comment by screig** [comment]
Thanks

**Comment by amaggiulli** [comment]
If I enable netstandard 2.0 got troubles in FastActivator class : DynamicMethod ILGenerator and LocalBuilder

**Comment by screig** [comment]
I did this, changing the TargetFramework and adding the package.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.12.0</VersionPrefix>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <DefineConstants>$(DefineConstants);QL_NEGATIVE_RATES</DefineConstants>
    <AssemblyName>QLNet</AssemblyName>
    <PackageId>QLNet</PackageId>
    <PackageVersion>1.12.0</PackageVersion>
    <Authors>Andrea Maggiulli</Authors>
    <Company />
    <Description>A free/open-source library for quantitative finance</Description>
    <Copyright>Copyright (c) 2008-2021 Andrea Maggiulli (a.maggiulli@gmail.com)</Copyright>
    <PackageLicenseUrl>https://github.com/amaggiulli/QLNet/blob/develop/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>http://github.com/amaggiulli/qlnet</PackageProjectUrl>
    <PackageTags>QLNet QuantLib quantitative finance financial</PackageTags>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
  </ItemGroup>


</Project>
```

Like I said I would have committed this as a branch, but seem to be blocked.

**Comment by amaggiulli** [comment]
yea that works , have to add back : 

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.0.1" />
  </ItemGroup>

**Comment by screig** [comment]
Cool

**Comment by amaggiulli** [comment]
now I have to fight with nuget/github deployement for multi-target 😄 , will ask you to verify once done thanks

**Comment by screig** [comment]
but why bother with multi deployment, with net standard it can go anywhere, no?

**Comment by amaggiulli** [comment]
Well, main reason is that I don't want to lose net6.0 optimizations, also I see many open source projects have dropped netstandard in favor of being full dotnet core since it is less limiting in what you can do.
Anyway, as netstandard2.0 is supported (via .net 4.6.2 still being in the live lifecycle), I will restore the multi-target to fix the issue you and maybe others could have.

**Comment by screig** [comment]
Well that makes sense, and I learnt something, thanks.
