### ISSUE TITLE
Update to .NET 8

### ISSUE THREAD

**Issue by amaggiulli** [amaggiulli/QLNet#283]

**Comment by jerhat** [comment]
Any ETA for [Release 1.14](https://github.com/amaggiulli/QLNet/milestone/5) ?

**Comment by amaggiulli** [comment]
Still working on some stuff, if you need NET 8 use [QLNet 1.13.1-preview.16](https://www.nuget.org/packages/QLNet/1.13.1-preview.16)

**Comment by jerhat** [comment]
Indeed waiting for .NET 8. Thanks for the pointer to the pre-release.
