### ISSUE TITLE
Please add a strong name to the distribution build

### ISSUE THREAD

**Issue by ivern** [amaggiulli/qlnet#3]
It'd be awesome if the distribution (including the NuGet package) could be strong named.  Any chance this could be done?  Thanks in advance...

**Comment by screig** [comment]
Could this please be reopened? @amaggiulli 

![image](https://user-images.githubusercontent.com/4292074/29612431-2dd6a794-87f9-11e7-87eb-29000fdd6ff2.png)

**Comment by igitur** [comment]
@screig Why do you need a strong named assembly? AFAIK, all the reasons punted way back in 2001 aren't really relevant anymore. Security certainly isn't applicable.

**Comment by igitur** [comment]
This is a good read about why signing assemblies isn't required anymore: https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/

**Comment by screig** [comment]
Hi

Well the article makes some good points. My reason for wanting it is the same as the first reason the author of the article gives:

- You want to enable your assemblies to be referenced by strong-named assemblies, or _you want to give friend access to your assemblies from other strong-named assemblies_.

However there is no statement in this article refuting how this particular aspect is no longer relevant or offering some 'modern' alternative. He goes on to quote how Microsoft remove the strong name in XAML Behaviors, mainly from what I see as a breaking change with regards to the Univeral Windows Platform. So in the edge case there is a limitation. Fine, but QLnet is not really targeting windows phone apps is it? This is the exception not the rule, Microsoft sign all (all; for all practical purposes) their other Dlls. In fact in my entire solution there is only one package that it not strongly signed. All these are signed:
    
- Newtonsoft

- RabbitMQ

- log4net

- MathNet

- NodaTime

- NPGSQL

- Every Single Microsoft package

If this article was true, then why are the vast majority (i'm going to go for 80%+ if not 90%) of packages on Nuget strongly signed. Out of interest when you open the install a Nuget package window, the packages are listed in order of popularity, how far down would one have to go to find the first non-signed dll/package? This in itself is not a reason to do it, however if the vast majority of ones peers are doing it, I think you need to have a very strong argument about why one would not do it.

I simply want to allow internal access to an assembly in a secure way? Please note here I am talking about internal access to the assembly that I develop, not QLNet. However to implement this all assemblies used, need to be strong named. 

Sean


See also
[best practices](https://msdn.microsoft.com/en-us/library/ms182127.aspx)
