### ISSUE TITLE
Amortization value incorrect values

### ISSUE THREAD

**Issue by mozts2005** [amaggiulli/qlnet#43]
Amortization value is not being calculated correctly on purchase date or maturity date. 

Will submit pull request with unit test.

**Comment by igitur** [comment]
I'm busy looking at this - just have to sort out some other  unit tests in the same class as well.

**Comment by igitur** [comment]
Hi @mozts2005 ,

Refer to issue #46 . Your tests use the AmortizingBond class, but we'd like to remove it. Would one of the remaining 3 similar classes suit your goal?

**Comment by mozts2005** [comment]
any class would work but the AmortizingBond class is currently the only one with the amortizationValue  method.
