### ISSUE TITLE
Calculation of CASH

### ISSUE THREAD

**Issue by igitur** [amaggiulli/qlnet#45]
Hi @amaggiulli 

In revision 361 in the old SVN project, I see that support for calculation of CASH values were added. However, I can't find any reference to these calculations in the QuantLib project. I'd like to keep the 2 projects in line as much as possible, so can you please explain what these CASH calculations are for? They don't seem to be used that much. If they really serve a purpose, I'll backport it to QuantLib.

**Comment by amaggiulli** [comment]
I will look at this and explain

**Comment by igitur** [comment]
?

**Comment by amaggiulli** [comment]
Sorry I forgot to comment , CASH is needed by some users of QLNet.

**Comment by igitur** [comment]
Do you have an example of where it's used? I'd like to backport it to
Quantlib then.

Francois Botha
