### ISSUE TITLE
AmortizingBond

### ISSUE THREAD

**Issue by igitur** [amaggiulli/qlnet#46]
Hi @amaggiulli 

in QLNet we have 4 classes for amortizing bonds: AmortizingBond, AmortizingCMSRateBond, AmortizingFixedRateBond and AmortizingFloatingRateBond.

In QuantLib the AmortingBond class doesn't exist. What is the purpose of this class if the other 3 already exist? If it's important, I want to backport it.

**Comment by amaggiulli** [comment]
Hi @igitur , they exists in Quantlib in the experimental folder.

**Comment by igitur** [comment]
I still can't find the AmortizingBond class:

https://github.com/lballabio/quantlib/tree/master/QuantLib/ql/experimental/amortizingbonds

**Comment by amaggiulli** [comment]
Ah sorry , you mean only the AmortizingBond class , it seems is not used also in QLNet ,I think can be removed

**Comment by amaggiulli** [comment]
I see now @mozts2005 used that for some tests , are u working on this ?
