### ISSUE TITLE
Vanilla Swap Pricer Ignores Index Fixing Days

### ISSUE THREAD

**Issue by OfirMarom** [amaggiulli/qlnet#52]
Hi @amaggiulli

I think I have found a bug becuase the vanilla swap pricer ignores fixing days of the index - it always uses the default which is 2. See my code below. If you value for 20 April 2015 you get an exception for a the fixing of 17 April 2015. Since the index has 0 fixing days I should not need the 17 April fixing.

I have looked through the source code. I am not sure why this line is commented out in the VanillaSwap.cs class but it appears to fix the problem if I uncomment it.

      legs_[1] = new IborLeg(floatSchedule, iborIndex)
                                     .withPaymentDayCounter(floatingDayCount)
            //.withFixingDays(iborIndex.fixingDays())
                                     .withSpreads(spread)
                                     .withNotionals(nominal)
                                     .withPaymentAdjustment(paymentConvention_);

Without this, what happens is that in the constructor of FloatingRateCoupon.cs class fixingDays is passed in with the default value of 2 and this line: 

fixingDays_ = fixingDays == default(int) ? index.fixingDays() : fixingDays;

subsequently always returns 2.         

Code to reproduce issue:

 Date tradeDate = new Date(17, Month.April, 2015);
            Calendar calendar = new UnitedKingdom();
            Date settlementDate = calendar.advance(tradeDate, 2, TimeUnit.Days, BusinessDayConvention.Following);
            Date maturityDate = calendar.advance(settlementDate, 5, TimeUnit.Years, BusinessDayConvention.Following);           
            Date valueDate = new Date(20, Month.April, 2015);
            Settings.setEvaluationDate(valueDate);
           

            List<Date> dates = new List<Date>();
            dates.Add(valueDate);
            dates.Add(valueDate + new Period(1,TimeUnit.Years));
            dates.Add(valueDate + new Period(2,TimeUnit.Years));
            dates.Add(valueDate + new Period(5,TimeUnit.Years));
            dates.Add(valueDate + new Period(10,TimeUnit.Years));
            dates.Add(valueDate + new Period(20,TimeUnit.Years));

            List<double> rates = new List<double>();
            rates.Add(0.01);
            rates.Add(0.01);
            rates.Add(0.01);
            rates.Add(0.01);
            rates.Add(0.01);
            rates.Add(0.01);

            var discountCurveHandle = new RelinkableHandle<YieldTermStructure>();

            var forecastCurveHandle = new RelinkableHandle<YieldTermStructure>();

            GBPLibor index = new GBPLibor(new Period(6, TimeUnit.Months), forecastCurveHandle);
         
            InterpolatedZeroCurve<Linear> zeroCurve = new InterpolatedZeroCurve<Linear>(dates,rates,new Actual360() , new Linear());

            var fixedSchedule =  new Schedule(settlementDate, maturityDate, new Period(1,TimeUnit.Years), calendar, BusinessDayConvention.Following, BusinessDayConvention.Following, DateGeneration.Rule.Forward, false);

            var floatSchedule = new Schedule(settlementDate, maturityDate, index.tenor(), calendar, BusinessDayConvention.Following, BusinessDayConvention.Following, DateGeneration.Rule.Forward, false);
     
            VanillaSwap swap = new VanillaSwap(VanillaSwap.Type.Payer, 1000000, fixedSchedule, 0.01, new Actual360(), floatSchedule, index, 0, new Actual360());

            discountCurveHandle.linkTo(zeroCurve);

            forecastCurveHandle.linkTo(zeroCurve);

            var swapEngine = new DiscountingSwapEngine(discountCurveHandle, false, null);

            swap.setPricingEngine(swapEngine);

            Console.WriteLine("Settlement Date is: " + settlementDate);
            Console.WriteLine("Fixing days of index is: " + index.fixingDays());
            Console.WriteLine("Therefore, we do not need a fixing for 17/04/2015 when we value on " + valueDate + " but we get this error");

          
            try
            {
               swap.NPV();  
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

Thanks
Ofir

**Comment by amaggiulli** [comment]
Fixed in commit dcfe0fab9e99a77e88ddc4cf671c79d52b604189 , in version 1.4.0.25 - ty Ofir
