### ISSUE TITLE
CashFlow / IRR and YTM

### ISSUE THREAD

**Issue by underwater** [amaggiulli/qlnet#61]
Just starting with this library, and wondering if someone can help with this use case question

I need to calculate the internal rate of return (IRR) , both for the reporting period (Period IRR) as well as the Annualized IRR for a portfolio.   I have already prepared  as SimpleCashFlows the 
- intial Value of the portfolio, 
- the contributions / withdrawals, 
- end Value of the portfolio.

Can I simply use CashFlows.yield(), i.e. the same method I would typically used for calculating YTM on a bond ?   If yes, what option should I use for compounding / frequency ?

**Comment by igitur** [comment]
@underwater This is probably not what you want to hear, but only @amaggiulli and I work on this project. I'm not sure about @amaggiulli , but I can't help you with the answer. I just don't know the entire library well enough. What I suggest is that you ask it on the QuantLib (the C++ version) mailing list. Once you get an answer there and QLNet and QuantLib give different values, let me know, and I'll ensure that QLNet is fixed to be aligned with QuantLib. Hope that is OK?
