### ISSUE TITLE
MultiAssetOption greeks are scalar

### ISSUE THREAD

**Issue by paveldiko** [amaggiulli/qlnet#65]
I am writing an instrument derived from MultiAssetOption class. The problem I have is that the greeks are declared as scalars in the MultiAssetOption while I need them to all the underlyings. Any suggestions on how to allow them to be vectors in my subclass - apart from effectively overriding entire MultiAssetOption class?

**Comment by amaggiulli** [comment]
Override class Results in your derived class :
```new public class Results : Instrument.Results```
also override fetch results :
 ```public override void fetchResults(IPricingEngineResults r)```
