### ISSUE TITLE
how to pricing American option with volatility surface?

### ISSUE THREAD

**Issue by mike1232** [amaggiulli/qlnet#66]
In the option examples, QLNet uses the flat term structures for r, q and volatility. how to use the curve term structures? in particular, how to set up a volatility surface and use the surface as input for the pricing engines? In QuantLib C++, you can create a wrapper:

boost::shared_ptr<BlackVolTermStructure> ForwardImpliedVolSurface(Date todaysDate, Date forwardDate, Calendar calendar, std::vector<Date> maturityArray, std::vector<Real> strikeArray, Matrix volatilityMatrix)
{
  // Handle to boost::shared_ptr
  DayCounter dayCounter = Actual365Fixed();
  boost::shared_ptr<BlackVarianceSurface> volatilitySurface(new BlackVarianceSurface(todaysDate, calendar, maturityArray, strikeArray, volatilityMatrix, dayCounter));
  Handle<BlackVolTermStructure> volatilitySurfaceH(volatilitySurface);

  // Volatility surface interpolation
  volatilitySurface->enableExtrapolation(true);

  // Change interpolator to bicubic splines
  volatilitySurface->setInterpolation<Bicubic>(Bicubic());

  // Forward implied volatility surface
  boost::shared_ptr<BlackVolTermStructure> forwardVolSurface(new ImpliedVolTermStructure(volatilitySurfaceH, forwardDate));

  return(forwardVolSurface);
}

how does QLNet achieve this?

Thanks
Mike

**Comment by amaggiulli** [comment]
BlackVarianceSurface atm is not implemented in QLNet.

**Comment by igitur** [comment]
I implemented `BlackVarianceSurface`. You can find it in the master branch. However, I don't have any test cases and I'm unsure how buggy my implementation is. @mike1232 , if you can provide some tests, it would help a lot.

**Comment by amaggiulli** [comment]
moved on Ver-1.6 branch

**Comment by igitur** [comment]
See #76
