### ISSUE TITLE
linear least squares regression

### ISSUE THREAD

**Issue by xiangtaoliu** [amaggiulli/qlnet#67]
In linearleastsquaresregression.cs,
        public LinearRegression(List<List<double>> x, List<double> y) {
            reg_ = new LinearLeastSquaresRegression<List<double>>(x, y, linearFcts(x.Count));
        }
linearFcts counts the number of explanatory variables, which shouldn't be the number of elements in x. It should be the number of elements in x[0]. 
x.count is actually the sample size.

**Comment by amaggiulli** [comment]
This is the code : 

```c#
        //! one dimensional linear regression
        public LinearRegression(List<double> x, List<double> y) {
            reg_ = new LinearLeastSquaresRegression<List<double>>(argumentWrapper(x), y, linearFcts(1));
        }    

        //! multi dimensional linear regression
        public LinearRegression(List<List<double>> x, List<double> y) {
            reg_ = new LinearLeastSquaresRegression<List<double>>(x, y, linearFcts(x.Count));
        }
```

if x is `` List<double> x`` it use linearFcts(1)
if x is `` List<List<double>> x`` it use linearFcts(x.Count)

is that wrong ? Can you explain more ?

**Comment by xiangtaoliu** [comment]
linearFcts determines the number of regression factors. The size of x is the size of the sample data. It is required for x.count ==y.count. The size of x[0] is the number of regression factors.

**Comment by amaggiulli** [comment]
Fixed https://github.com/amaggiulli/qlnet/commit/6777be57ce4a5c1df0a9ece86c1c34bb8af5ae8d
