### ISSUE TITLE
QLNet Current State

### ISSUE THREAD

**Issue by ohm77** [amaggiulli/qlnet#68]
I have been trying to use both QLNet and Quantlib (C++) library. I find that QLNet is not updated with all functionalities and features as available in Quantlib. Is there an active development effort for QLNet? If yes, then I have a few questions to ask regarding QLNet, else it might be better to raise these questions on Quantlib forum. Thank you

**Comment by igitur** [comment]
Well, @amaggiulli is the only one who understands the entire codebase. I joined the project mid 2014 and started porting over some of the missing parts of QuantLib which were relevant to my job. But QuantLib is evolving all the time and it's difficult to keep up to date with a small team. 

What would help, is if you can identify which parts you want implemented. If you can port the unit tests that would be better and if you can port over the actual implementation that would be first prize.

**Comment by amaggiulli** [comment]
Feel free to ask everything here , also if you need some part of Quantlib still not converted.
If your questions are about QLNet or C# is useless to ask in Quantlib forum, if your questions instead 
are about financial algos you can try on both forum.
