### ISSUE TITLE
validation of bond risk analytics calculations

### ISSUE THREAD

**Issue by underwater** [amaggiulli/qlnet#70]
i am wondering if anyone has encountered any accuracy problems in using the quantlib for computing bond risk analytic metrics including modified duration, Macaulay duration and convexity.   
the result do not match a reference those obtained from an industry-standard 3rd party commercial library used on our production system and i was wondering if anyone has encountered any such issues

**Comment by amaggiulli** [comment]
Can you detail more ? With some example we can do some test case to checks numbers.

**Comment by underwater** [comment]
Sure, I should be back at work end of this week, and will to post a sample failing test.   As far as I could see the numbers matched only on coupon dates but differed slightly when there is an accrued interest

**Comment by amaggiulli** [comment]
Hi @underwater , any news on that ?
