### ISSUE TITLE
Garman Kohlagen Process ctor in BlackScholesProcess

### ISSUE THREAD

**Issue by bleonardo1** [amaggiulli/qlnet#71]
There's probably an error in this ctor.
    public class GarmanKohlagenProcess : GeneralizedBlackScholesProcess {
        public GarmanKohlagenProcess(Handle<Quote> x0,
                                     Handle<YieldTermStructure> foreignRiskFreeTS,
                                     Handle<YieldTermStructure> domesticRiskFreeTS,
                                     Handle<BlackVolTermStructure> blackVolTS)
            : this(x0, foreignRiskFreeTS, domesticRiskFreeTS, blackVolTS, new EulerDiscretization()) { }
        public GarmanKohlagenProcess(Handle<Quote> x0, Handle<YieldTermStructure> foreignRiskFreeTS,
                                     Handle<YieldTermStructure> domesticRiskFreeTS,
                                     Handle<BlackVolTermStructure> blackVolTS, IDiscretization1D d)
            : base(x0, foreignRiskFreeTS, foreignRiskFreeTS, blackVolTS, d) { }
    }
it should be.
        public GarmanKohlagenProcess(Handle<Quote> x0, Handle<YieldTermStructure> foreignRiskFreeTS,
                                     Handle<YieldTermStructure> domesticRiskFreeTS,
                                     Handle<BlackVolTermStructure> blackVolTS, IDiscretization1D d)
            : base(x0, foreignRiskFreeTS, domesticRiskFreeTS, blackVolTS, d) { }
    }

**Comment by amaggiulli** [comment]
Fixed in branch 1.6 => https://github.com/amaggiulli/qlnet/commit/5ef847f8421936ce15753e2d042ae1180602a274 . Thx @bleonardo1
