### ISSUE TITLE
request: example with MaxBasketPayoff

### ISSUE THREAD

**Issue by akasolace** [amaggiulli/qlnet#72]
First I would like to thanks the developer for that quality project, it is really much appreciated. 
I was looking for pricing European option on the max of two assets. I can see that in the class payoff there is mention of a MaxBasketPayoff. Is it usuable? If it is the case would you mind to add an example of how to use it? I am currently developing in csharp an implementation of Stulz and I wanted to check the result with a MonteCarlo. 
Thank you for your help and thank again for the great work.

**Comment by amaggiulli** [comment]
Hi akasolace , 
thank you for your appreciation and welcome to QLNet. 
I have done the Stulz engine code with a basket option test that I hope will help you on your work. You can find it in this commit : https://github.com/amaggiulli/qlnet/commit/79cdddbab2a1fa0a71e2fd2f9f21c5df7aba1a86
in the 1.6 development branch.Let me know how it goes.

**Comment by akasolace** [comment]
Hey amaggiulli,
Thank you very much for the prompt reply.
It is exactly what is was looking for. I will do the check against my own pricing library and I will provide you feedback. 
I already validated my cbvn (Ganz algorithm) and kirk implementation many time. I will also check stulz result against my closed formula implementation. Since yesterday I did perform test against matlab implementation of Stulz and I got error of between 0.1 and 0.3 % 
I will come back to you 
cheers

**Comment by akasolace** [comment]
Ok so yesterday I looked at your code and :
     - I realized your implementation was also analtyc, I previously thought it was a mc
     - I ran your testing file using my oww stulz implementation (I removed the kirk testing)
     - the test failed on the 8th example (for the first seven my results were perfectly align with yours and for info differs from matlab result)
      - for the 8th test I am sure the bug should lies in my bcnd implementation, I will have a look asap
(for info I did test my cbnd function on 200 examples and it was working perfectly against all of them)

As soon as I have solve that issue I will also get the greeks (out of analytic calculation) and will share the result with you, hence if at some stage you want to incorpoate greek calculation you will some test samples.

I keep you postded 

cheers

**Comment by amaggiulli** [comment]
Great , for now I close this issue then.

**Comment by akasolace** [comment]
Hello amaggiuli,
So yesterday I changed my cbnd implementation, it gained precision and it solved my issue. 
By the way I modified my unit test for cbnd and I ran it within qlnet v1.6 and the test passed with qlnet implementation of cbnd 
Now the unit test fails on test 24 (the first test with T=0.5). Thing is that on that one my value match exactly the result of Matlab (which differs from qlnet).  
I notice that my test code is based on ACT/365 whereas your test code assumes ACT/360 but in my view it should not change anything considering the maturity is expressed in years, do you agree with that?
However I noticed that if I assume ACT/360 for the IR and ACT/365 for the volatility then I get much closer from qlnet result (but for what I can see in your code is it ACT/360 for both).
I will try to investigate further, in the meantime if you have an idea of were the difference can come from please let me know ....

**Comment by akasolace** [comment]
I just checked agains QuantLib, and behaviour is the same.
Hence I will try to get answers directly from Quantlib forum.

**Comment by akasolace** [comment]
ok this time the subject is really closed :-)

**Comment by igitur** [comment]
@akasolace If you post the query on the QuantLib forum, let me know. I want to follow it there too.

**Comment by akasolace** [comment]
I opened the bug in QuantLib forum ... and it was close by Luigi
(https://github.com/lballabio/QuantLib/issues/47)
Issue was on my side as I more or less copied and paste your unit test into my code without thinking 
This time everything is fine, my code passed your kirk and Stulz test unit example.
If at some point you want to implement some Greeks calculation and are looking for test data, I would be happy to provide those as there is limited data in the literature (i.e in your test unit I could complete your stulz and kirk array with some greeks computed out of my code)
