### ISSUE TITLE
American Option pricing with Discrete Dividend

### ISSUE THREAD

**Issue by ohm77** [amaggiulli/QLNet#77]
I am looking for American option pricing with discrete dividend via Monte Carlo or Binomial option. While quantlib/qlnet has the finite difference implementation for the same, I am curios if quantlib has functionalities in this regards.

**Comment by amaggiulli** [comment]
Quantlib or QLNet ?

**Comment by ohm77** [comment]
Either one, I did not come across DividendVanillaOption (the option model that supports discrete dividends) being used anywhere else apart from Finite Difference based pricing.

I would highly appreciate If you could point me to discrete dividend implementation via Monte Carlo or Binomial model either in Quantlib or QLNet.
