### ISSUE TITLE
Assertions failing in EquityOption sample on timeSteps==null || timeStepsPerYear==null

### ISSUE THREAD

**Issue by tomislav-t** [amaggiulli/qlnet#84]
Hi,

I am new to QLNet and was trying to run the EquityOption sample. It now fails on an assertion in the MCVanillaEngine:

         Utils.QL_REQUIRE( timeSteps == null || timeStepsPerYear == null, () =>
                    "both time steps and time steps per year were provided" );

The variables are declared as int and not as int? meaning they can never have the null value.

I think MakeMCEuropeanEngine should be modified to declare steps_, stepsPerYear_, samples_ and maxSamples_ as int?.

Am I right, should I modify the library like this?

Tomislav

**Comment by igitur** [comment]
Yes, I think you're right.

**Comment by amaggiulli** [comment]
Working on it

**Comment by amaggiulli** [comment]
Fixed in 3eac6d3949e0e3cb2aa1ee531847385f0f18dd86

**Comment by tomislav-t** [comment]
Thanx, I can see it does not fail on these asserts anymore...

Tomislav

On 23 May 2016 at 14:09, Andrea Maggiulli <notifications@github.com> wrote:

> Fixed in 3eac6d3
> <https://github.com/amaggiulli/qlnet/commit/3eac6d3949e0e3cb2aa1ee531847385f0f18dd86>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/amaggiulli/qlnet/issues/84#issuecomment-220962743>
>



-- 
Tomislav Trajkovski
Managing Director
Applify BV

Head Office, Delft
Rotterdamseweg 183C
2629 HD Delft
The Netherlands
Telephone: +31 (0)15 2120684
Cell: +31 (0) 637 376974
Fax: +31 (0)15 2121517
Email: tomt@applify.com
