### ISSUE TITLE
Serialisation 

### ISSUE THREAD

**Issue by screig** [amaggiulli/qlnet#93]
Hi
Firstly thanks for your great work! In the future would it be possible to add serialisation attributes to the classes. I would like the ability to be able to serialise term structures for later use. 
Thanks
Sean

**Comment by amaggiulli** [comment]
in todo list . Btw you can contribute on this , if you need help on how contribute ask here .

**Comment by screig** [comment]
I would be happy yo contribute. i took a fork of the code and added serialization attributes all over it, off course that did not work. Where would you start with this?
