### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by leo90skk** [amaggiulli/qlnet#97]
I want to use this app in an .NET Core application. Can you please add support for it?

**Comment by leo90skk** [comment]
it took to long for me, so i did it by myself.

**Comment by amaggiulli** [comment]
branch develop now is .net core compatible .

**Comment by screig** [comment]
Is there a net core nuget package?

**Comment by leo90skk** [comment]
.net core is not a nuget package, it is a new base framework which supports cross platform development / compilation

**Comment by screig** [comment]
Hi
Yes, I know that thanks, let me be a bit more clear. If you look at this Nuget package:

https://www.nuget.org/packages/Newtonsoft.Json/9.0.2-beta2

You can see two things, firstly that the Json.net project has been ported to Net.Core and also on building the Nuget package a version to support Net.Core has been included. Such that if one is working to that framework (net core) one can can get the Json.Net package from Nuget. 

What I am asking for qualification for is that am I correct in thinking that whilst support for Net.Core has been coded, the Nuget package has been built only to support net 4.0 and not Net.Core?

thanks
Sean

**Comment by amaggiulli** [comment]
Yes , actually only .net 4.0 version is on Nuget , 
I need some support to include the net core version in the same build .

**Comment by screig** [comment]
I can take a look that if you wish?

**Comment by amaggiulli** [comment]
Sure

**Comment by amaggiulli** [comment]
I will create new issue to handle this enhancement.
